services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Derhansen\XclassDi\:
    resource: '../Classes/*'

  TYPO3\CMS\Belog\Controller\BackendLogController: '@Derhansen\XclassDi\Controller\ExtendedBackendLogController'

